## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('drone', ['internet', 'wifi', 'applications','olsr','config-store','stats'])
    module.source = [
        'model/collision-avoidance-app.cc',
        'helper/collision-avoidance-helper.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'drone'
    headers.source = [
        'model/collision-avoidance-app.h',
        'helper/collision-avoidance-helper.h',
        ]
